name: Deploy to Render on Push

on:
  push:
    branches:
      - development  # Change to the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Render Deploy (Automatic on Push)
        run: |
          echo "Pushing changes to trigger automatic Render deployment..."
          # No direct API call needed here. Render will automatically deploy
          # when it detects changes on the connected repository and branch.
          echo "Make sure your Render services are connected to this repository"
          echo "and set to automatically deploy on pushes to the 'development' branch."